### ISSUE TITLE
Add "Homepage" button or menu item

### ISSUE THREAD

**Issue by edbrannin** [jparnell8839/AlwaysOnTop#1]
I'm pretty sure I've been using this for a few months, and I just tried to tell a friend how to get it and I had some trouble finding my way back here.

**Comment by jparnell8839** [comment]
Good idea! I will try to add this functionality ASAP!

**Comment by jparnell8839** [comment]
Implemented! Please download the new version.

**Comment by edbrannin** [comment]
Any plan to upload a binary release?

**Comment by edbrannin** [comment]
Whoops, I see it in the repo now -- just isn't listed on the Releases page.
