### ISSUE TITLE
Turn of system sounds checkbox

### ISSUE THREAD

**Issue by stephen147** [jparnell8839/AlwaysOnTop#10]
In settings is it possible to turn of system sounds.

Looking farward to the always put these windows on top feature!!

Thanks for this.

**Comment by stephen147** [comment]
Under win 10. Settings>Notifications and actions you can disable it from appearing in the notications side bar.

Would still be nice to have a setting.

**Comment by jparnell8839** [comment]
Are you referring to the balloon tips on load / registering a hotkey / performing hotkey action? I'm on the Anniversary Edition of Windows 10, and when I disable it, the icon remains but the balloon tips do not.

Just trying to make sure I understand what you're requesting; I would be more than happy to implement this.

**Comment by cshaa** [comment]
I guess that's what Stephen means – you can disable it in Windows settings and it works fine, but it would be nice if you could disable notifications also in your app's settings. Furthermore, my humble opinion is that notification on app startup is redundant or even disturbing. Cool app tho, looking forward for more stable builds ;)

**Comment by stephen147** [comment]
Yeah, so when I active the App with a hotkey. The ballon appears but creates that really loud notification sound (which I've searched and it's a bug) as I've tried to lower my system volume but that notification still is really loud an annoying.

If you can add an option to disable the sound 'and or' the ballon notification that would be great.

Have you an ETA on when the 'always put these windows on top feature'?

FYI on my OS: I just done a fresh install of win10 there a month ago with all upgrades to date.

**Comment by jparnell8839** [comment]
Proposed for 0.5.1

**Comment by jparnell8839** [comment]
Feature implemented in [Version 0.5.1](https://github.com/jparnell8839/AlwaysOnTop/releases/tag/0.5.1).

![image](https://cloud.githubusercontent.com/assets/5015689/21739187/016018da-d462-11e6-88ca-fccb9d181b02.png)

I cannot distinguish between the sound and the balloon tip; one cannot exist without the other. However, this should give you a bit of a cleaner experience.

Let me know how you like this, and if you have any further requests / bugs, please submit a new issue. Thanks guys!

**Comment by jparnell8839** [comment]
Also, @stephen147 , I do not have an ETA on the persistent windows always remaining on top; my current focus is delving into the GitHub API to see if I can find a method of checking for new releases. Octokit seems promising, but their documentation is very behind and hasn't caught up to the codebase. Persistent windows will be my next focus after the updater.

**Comment by stephen147** [comment]
Thank you. This is a great app. Thanks.
