### ISSUE TITLE
Add hotkey for toggling

### ISSUE THREAD

**Issue by Keith94** [jparnell8839/AlwaysOnTop#2]
I'm looking for a hotkey-based solution for toggling always on top for windows. Can it be added here?

**Comment by jparnell8839** [comment]
Good idea! I will try to implement this ASAP

**Comment by jparnell8839** [comment]
Proposed for 0.3

**Comment by jparnell8839** [comment]
I just released v. 0.3.0, which unfortunately did not include your enhancement request. I have re-written the project in C#, which makes it not as resource intensive and will hopefully allow me greater flexibility to implement your feature request.

**Comment by Keith94** [comment]
All right. I couldn't get 0.3.0 to run btw, I think it crashes on startup.

**Comment by jparnell8839** [comment]
Do you have .Net 4.5.2 installed? That would be the only prerequisite it needs... I'll take a look at it in a bit

**Comment by Keith94** [comment]
Apparently it tells me: `.NET Framework 4.5.2 or a later update is already installed on this computer.`

**Comment by jparnell8839** [comment]
All right. Could be a build issue. I'll take a look at it in a couple hours

**Comment by jparnell8839** [comment]
Please try again with this attached version. It will likely crash still, but now there should be a file in the same location called AoT_Error.log when it does; I need that error log to see why it's crashing.
[AlwaysOnTop.zip](https://github.com/jparnell8839/AlwaysOnTop/files/679388/AlwaysOnTop.zip)

**Comment by Keith94** [comment]
This is the contents:

`2016.12.30 05:18:16 PM: Could not find file 'C:\Users\Keith\Downloads\AlwaysOnTop\icon.ico'.`

**Comment by jparnell8839** [comment]
Awesome, I figured out what it is; I overlooked one of the icon files and it wasn't embedded into the exe. I am syncing the build with GitHub now and will create a new release once it's available, 0.3.1

**Comment by Keith94** [comment]
Can confirm it works.

**Comment by jparnell8839** [comment]
Feature enabled with [version 0.5.0](https://github.com/jparnell8839/AlwaysOnTop/releases/tag/0.5.0). Please note: This will not work with Explorer shell windows or elevated (admin) windows. The Windows key cannot be assigned as a hotkey. Standard common hotkeys (such as Alt + Tab, Ctrl + V, etc) that are used almost globally in most Windows applications have been disabled.

Please advise if this works to your satisfaction, and if you have any issues, submit another Issue here on GitHub.

Thanks for your patience!
