### ISSUE TITLE
keyboard issues after install of AlwaysOnTop

### ISSUE THREAD

**Issue by ZirconfleX** [jparnell8839/AlwaysOnTop#21]
Hi,

Just installed AlwaysOnTop on Windows 10 Enterprise.
When I activate it for a window, it does what it needs to do.
   The indicated windows stay's always on top of others and of the taskbar but:
When I slide the always on tow window to a side to type or do something with the keyboard, the keyboard is dead.
I need to exit AlwaysOnTop to get my keyboard back.

As long as I have not used AlwaysOnTop, keyboard works fine in all windows.

Regards,

Marc

**Comment by alvarorodriguezestruch** [comment]
Same problem here, at the moment that you pin a window, keyboard is not working anywhere.

**Comment by wolfymaster** [comment]
Just experienced this today after installing the latest build. It seems like two processes are launching. When I exit out of the system tray - I can exit once, the tray icon persists, but I get the keyboard back. Then I can exit out of the system tray icon once again.

**Comment by ghost** [comment]
@wolfymaster Experiencing the same.

**Comment by prokn4h** [comment]
Same.

**Comment by jmcd040** [comment]
Same. Uninstalled the program, but would really like to see it work.

**Comment by Frioo** [comment]
Same here. After quitting the program the keyboard worked again.

**Comment by clouedoc** [comment]
Same issue here. Selecting chromium with always on top makes keyboard unusable.

**Comment by Wingee** [comment]
same here! any updates?

**Comment by perezed00** [comment]
If you are experiencing this issue, downgrade to version 0.5.1 - that solved my problem on Windows 10
